### ISSUE TITLE
column is not getting hidden

### ISSUE THREAD

**Issue by Naveen2605** [WRidder/Backgrid.ColumnManager#1]
Hi, 

I have made some changes on the plugin (removed dependencies code for underScore, backbone, backgrid). those dependencies i have already included those dependencies in my projects.

I able to change the column configuration "Renderable" true and false
but unable to hide the column.

should i redraw the backgrid?

**Comment by WRidder** [comment]
@Naveen2605 No, you should not have to rerender the grid. What should be happening is that the columnmanager changes the `renderable` property on the column. That should trigger backgrid to either show or hide the column. That is actually native functionality. So can you check whether the renderable attribute is properly set on the column?

**Comment by WRidder** [comment]
Closed issue due to inactivity
